alter table VERTICO_CLOUD_APP add constraint FK_VERTICO_CLOUD_APP_MACHINE foreign key (MACHINE_ID) references VERTICO_VOLUNTEER(ID);
create index IDX_VERTICO_CLOUD_APP_MACHINE on VERTICO_CLOUD_APP (MACHINE_ID);
