alter table VERTICO_VOLUNTEER add constraint FK_VERTICO_VOLUNTEER_LINKED_USER foreign key (LINKED_USER_ID) references VERTICO_USER(ID);
create index IDX_VERTICO_VOLUNTEER_LINKED_USER on VERTICO_VOLUNTEER (LINKED_USER_ID);
